# Generated by Django 4.2.11 on 2025-06-21 06:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorderproduct',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
