# Generated by Django 4.2.11 on 2025-07-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0005_preorder_cost_price_preorder_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='preorder_product',
        ),
    ]
