# Generated by Django 5.2.5 on 2025-10-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0006_remove_preorder_preorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('CASH', 'Cash'), ('CARD', 'Card'), ('OTHER', 'Other')], default='COD', max_length=10),
        ),
        migrations.AddField(
            model_name='preorder',
            name='preorder_type',
            field=models.CharField(choices=[('shop_preorder', 'Shop Preorder'), ('online', 'Online')], default='shop_preorder', max_length=20),
        ),
        migrations.AddField(
            model_name='preorder',
            name='shipping_address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('ONLINE', 'Online')], default='MANUAL', max_length=10),
        ),
    ]
