# Generated by Django 5.2.5 on 2025-11-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0008_preorder_delivery_charge_preorder_delivery_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='preorder_type',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='source',
        ),
    ]
