services:
  - type: web
    name: rms-backend
    env: python
    rootDir: rms_backend/project
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    preDeployCommand: python manage.py migrate --noinput
    startCommand: gunicorn rms.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: rms.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      # Database variables must be set in Render dashboard or linked to a managed DB
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false




