# Generated by Django 4.2.11 on 2025-06-13 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('expenses', 'Expenses Report'), ('inventory', 'Inventory Report'), ('customers', 'Customers Report'), ('categories', 'Categories Report'), ('profit_loss', 'Profit & Loss Report'), ('product_performance', 'Product Performance Report')], max_length=50)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metric_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='reports.report')),
            ],
            options={
                'ordering': ['metric_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='reports.report')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['date_from', 'date_to'], name='reports_rep_date_fr_12c9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['is_favorite'], name='reports_sav_is_favo_09ec2f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmetric',
            index=models.Index(fields=['metric_name'], name='reports_rep_metric__90e314_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmetric',
            index=models.Index(fields=['metric_type'], name='reports_rep_metric__a0e720_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdatapoint',
            index=models.Index(fields=['date'], name='reports_rep_date_1e8c45_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdatapoint',
            index=models.Index(fields=['category'], name='reports_rep_categor_ebf73d_idx'),
        ),
    ]
