# Generated by Django 5.2.5 on 2025-10-27 08:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0012_product_is_featured_product_is_new_arrival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('logo_text', models.CharField(blank=True, help_text='Text logo if no image', max_length=100, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='site_logo/')),
                ('logo_text', models.CharField(blank=True, max_length=100, null=True)),
                ('hero_badge_text', models.CharField(default='New Collection 2024', max_length=100)),
                ('hero_heading_line1', models.CharField(default='FIND', max_length=100)),
                ('hero_heading_line2', models.CharField(blank=True, default='CLOTHES', max_length=100, null=True)),
                ('hero_heading_line3', models.CharField(blank=True, default='THAT', max_length=100, null=True)),
                ('hero_heading_line4', models.CharField(blank=True, default='Matches', max_length=100, null=True)),
                ('hero_heading_line5', models.CharField(blank=True, default='YOUR STYLE', max_length=100, null=True)),
                ('hero_description', models.TextField(blank=True, default='Browse through our diverse range of meticulously crafted garments, designed to bring out your individuality and cater to your sense of style.', null=True)),
                ('hero_primary_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('hero_secondary_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('stat_brands', models.CharField(default='200+', max_length=50)),
                ('stat_products', models.CharField(default='2,000+', max_length=50)),
                ('stat_customers', models.CharField(default='30,000+', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Settings',
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discount_type', models.CharField(choices=[('APP_WIDE', 'App-Wide Discount'), ('CATEGORY', 'Category Discount'), ('PRODUCT', 'Product Discount')], default='APP_WIDE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount percentage (0.01 to 100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SCHEDULED', 'Scheduled')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Required for CATEGORY discount type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='inventory.category')),
                ('online_category', models.ForeignKey(blank=True, help_text='Online category for ecommerce discounts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='inventory.onlinecategory')),
                ('product', models.ForeignKey(blank=True, help_text='Required for PRODUCT discount type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
