# Generated by Django 5.2.5 on 2025-11-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_deliverysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysettings',
            name='inside_gazipur_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
