# Generated by Django 5.2.5 on 2025-12-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_homepagesettings_footer_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title (use \\n for line breaks)', max_length=200)),
                ('subtitle', models.TextField(blank=True, max_length=500, null=True)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('image', models.ImageField(help_text='Hero slide background image', upload_to='hero_slides/')),
                ('bg_color', models.CharField(choices=[('bg-slate-950', 'Slate 950'), ('bg-orange-950', 'Orange 950'), ('bg-purple-950', 'Purple 950'), ('bg-emerald-950', 'Emerald 950'), ('bg-slate-900', 'Slate 900'), ('bg-blue-950', 'Blue 950'), ('bg-red-950', 'Red 950'), ('bg-green-950', 'Green 950')], default='bg-slate-950', max_length=50)),
                ('layout', models.CharField(choices=[('clean-left', 'Clean Left'), ('centered-clean', 'Centered Clean'), ('split-clean', 'Split Clean'), ('image-showcase', 'Image Showcase'), ('bold-left', 'Bold Left')], default='clean-left', max_length=50)),
                ('title_class', models.CharField(default='text-5xl sm:text-6xl md:text-7xl lg:text-8xl xl:text-9xl font-black text-white leading-tight tracking-tighter', help_text='CSS classes for title styling', max_length=200)),
                ('subtitle_class', models.CharField(default='text-sm sm:text-base text-white/80 max-w-lg leading-relaxed', help_text='CSS classes for subtitle styling', max_length=200)),
                ('stats', models.JSONField(blank=True, default=list, help_text="Array of stats objects: [{'value': '200+', 'label': 'Brands'}]")),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
