# Generated by Django 5.2.5 on 2026-01-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Supports rich text/HTML', null=True)),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('cta_text', models.CharField(default='Shop Now', max_length=50)),
                ('cta_url', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo_modals/')),
                ('layout', models.CharField(choices=[('centered', 'Centered'), ('split-left', 'Split Left (Image Left)'), ('split-right', 'Split Right (Image Right)'), ('full-cover', 'Full Cover Image')], default='centered', max_length=50)),
                ('color_theme', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('brand', 'Brand Colors')], default='light', max_length=50)),
                ('display_rules', models.JSONField(blank=True, default=dict, help_text='Rules: timer, exit_intent, first_visit etc.')),
                ('targeting_rules', models.JSONField(blank=True, default=dict, help_text='Device and User targeting rules')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotional Modal',
                'verbose_name_plural': 'Promotional Modals',
                'ordering': ['-created_at'],
            },
        ),
    ]
