# Generated by Django 5.2.5 on 2026-02-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_promotionalmodal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalmodal',
            name='layout',
            field=models.CharField(choices=[('centered', 'Centered'), ('split-left', 'Split Left (Image Left)'), ('split-right', 'Split Right (Image Right)'), ('full-cover', 'Full Cover Image'), ('image-only', 'Image Only')], default='centered', max_length=50),
        ),
    ]
