# Generated by Django 5.2.5 on 2026-02-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_promotionalmodal_layout'),
        ('inventory', '0015_migrate_online_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='category',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='online_category',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.AddField(
            model_name='discount',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Required for CATEGORY discount type', related_name='discounts', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='discount',
            name='online_categories',
            field=models.ManyToManyField(blank=True, help_text='Online category for ecommerce discounts', related_name='discounts', to='inventory.onlinecategory'),
        ),
        migrations.AddField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Required for PRODUCT discount type', related_name='discounts', to='inventory.product'),
        ),
    ]
