# Generated by Django 4.2.11 on 2025-06-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_size_type_productvariation_color_hax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNISEX', 'Unisex')], default='UNISEX', max_length=6),
        ),
        migrations.AddField(
            model_name='product',
            name='size_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
