# Generated by Django 4.2.11 on 2025-07-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_productvariation_color_hax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('GIFT', 'Gift Transaction'), ('ADJ', 'Adjustment')], max_length=4),
        ),
    ]
