# Generated by Django 5.2 on 2026-02-13 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_product_ecommerce_statuses'),
        ('online_preorder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePreorderVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='IN_PROGRESS', max_length=16)),
                ('total_units', models.IntegerField(default=0)),
                ('verified_units', models.IntegerField(default=0)),
                ('skipped_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('online_preorder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='online_preorder.onlinepreorder')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_preorder_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePreorderVerificationScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('result', models.CharField(choices=[('MATCHED', 'Matched'), ('NOT_IN_ORDER', 'Not In Order'), ('OVER_SCAN', 'Over Scan')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='online_preorder.onlinepreorderverification')),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePreorderVerificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('ordered_qty', models.IntegerField(default=0)),
                ('verified_qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_preorder_verification_items', to='inventory.product')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='online_preorder.onlinepreorderverification')),
            ],
            options={
                'unique_together': {('verification', 'sku')},
            },
        ),
    ]
