# Generated by Django 6.0.5 on 2026-08-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_preorder', '0003_coupon_pricing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepreorder',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='is_fake',
            field=models.BooleanField(default=False, help_text='Marked as fake order or fake customer'),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='steadfast_consignment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='steadfast_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='steadfast_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
