# Generated by Django 6.0.5 on 2026-08-24 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_preorder', '0004_onlinepreorder_cancel_reason_onlinepreorder_is_fake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepreorder',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='fbc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='fbclid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='fbp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='purchase_event_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='purchase_event_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='risk_level',
            field=models.CharField(default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='utm_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='utm_term',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MetaEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255)),
                ('event_name', models.CharField(default='Purchase', max_length=100)),
                ('action_source', models.CharField(default='website', max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped / Already Sent')], default='SUCCESS', max_length=30)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('online_preorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_event_logs', to='online_preorder.onlinepreorder')),
            ],
        ),
    ]
