# Generated by Django 5.2 on 2026-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('online', 'Online'), ('both', 'Both')], default='shop', max_length=10),
        ),
    ]
