# Generated by Django 6.0.5 on 2026-08-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fake_notes',
            field=models.TextField(blank=True, help_text='Reason or notes for flagging as fake', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_flagged_fake',
            field=models.BooleanField(default=False, help_text='Flagged as a fake customer or fraudulent buyer'),
        ),
    ]
