# Generated by Django 4.2.11 on 2025-06-21 05:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0003_alter_supplier_email'),
        ('inventory', '0005_remove_preorderproduct_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreorderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('expected_arrival_date', models.DateField()),
                ('max_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_orders', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='preorder_products/')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=10)),
                ('size_type', models.CharField(blank=True, max_length=50, null=True)),
                ('size_category', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNISEX', 'Unisex')], default='UNISEX', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preorder_products', to='inventory.category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preorder_products', to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PreorderVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='Standard', max_length=50)),
                ('color', models.CharField(default='Default', max_length=50)),
                ('color_hax', models.CharField(default='#FFFFF', max_length=50)),
                ('max_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_orders', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preorder_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='preorder.preorderproduct')),
            ],
            options={
                'unique_together': {('preorder_product', 'size', 'color')},
            },
        ),
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DEPOSIT_PAID', 'Deposit Paid'), ('FULLY_PAID', 'Fully Paid'), ('ARRIVED', 'Arrived'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preorder_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='preorder.preorderproduct')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='preorder.preordervariation')),
            ],
        ),
    ]
