# Generated by Django 4.2.11 on 2025-07-04 12:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorder', '0003_remove_preorder_quantity_remove_preorder_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='preorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
