# Generated by Django 4.2.11 on 2025-06-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='color_hax',
            field=models.CharField(default='#FFFFF', max_length=50),
        ),
    ]
