# Generated by Django 4.2.11 on 2025-06-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_preorderproduct_preordervariation_preorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorderproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='preorderproduct',
            name='supplier',
        ),
        migrations.AlterUniqueTogether(
            name='preordervariation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='preordervariation',
            name='preorder_product',
        ),
        migrations.DeleteModel(
            name='Preorder',
        ),
        migrations.DeleteModel(
            name='PreorderProduct',
        ),
        migrations.DeleteModel(
            name='PreorderVariation',
        ),
    ]
