# Generated by Django 4.2.11 on 2025-05-29 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_supplier_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='color',
            field=models.CharField(default='Default', max_length=50),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'size', 'color')},
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='price_adjustment',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='variation_code',
        ),
    ]
