# Generated by Django 4.2.11 on 2025-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_preorderproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='color_hax',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
    ]
