# Generated by Django 5.2.5 on 2025-10-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productvariation_chest_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='color_hax',
            field=models.CharField(default='#ffff', max_length=50, null=True),
        ),
    ]
