# Generated by Django 5.2.5 on 2025-10-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_gallery_color_hax'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='height',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
