# Generated by Django 5.2.5 on 2025-10-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_productvariation_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='assign_to_online',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='assign_to_online',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
