# Generated by Django 5.2.5 on 2026-01-25 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_onlinecategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online_categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='inventory.onlinecategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='online_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_old', to='inventory.onlinecategory'),
        ),
    ]
