# Generated by Django 5.2.5 on 2026-01-25 12:59

from django.db import migrations

def migrate_online_categories(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    for product in Product.objects.all():
        if product.online_category:
            product.online_categories.add(product.online_category)

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_product_online_categories_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_online_categories),
    ]
