# Generated by Django 5.2.5 on 2026-02-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_productstatus'),
        ('inventory', '0016_onlinecategory_gender_alter_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ecommerce_statuses',
            field=models.ManyToManyField(blank=True, related_name='products', to='ecommerce.productstatus'),
        ),
    ]
