# Generated by Django 4.2.11 on 2025-08-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, help_text='Customer ranking based on total sales', null=True),
        ),
    ]
