# Generated by Django 5.2.5 on 2026-02-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_gifted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('online_preorder', 'Online Preorder'), ('offline_preorder', 'Offline Preorder (Just Preorder)')], default='shop', max_length=20),
        ),
    ]
