# Generated by Django 4.2.11 on 2025-06-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_vendor_expensecategory_budget_alter_expense_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='budget',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
